#!/bin/bash

#SBATCH --job-name=pythonenv        # Job name
#SBATCH --output=pythonenv.%j.out   # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=8           # Schedule 8 cores (includes hyperthreading)
#SBATCH --time=01:00:00             # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge        # Get any available node

echo "Running on $(hostname):"
module load Anaconda3  # Load anaconda

# Accept terms and conditions
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main
conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

# Init anaconda (in the HPC, prefer to use the following instead of 'conda init')
eval "$(conda shell.bash hook)"

ENV_NAME='myenv'
if ! conda env list | grep -q "$ENV_NAME"; then
    echo 'Creating new conda env...'
    conda create --name "$ENV_NAME" -y
    echo 'Created'
else
    echo "Environment '$ENV_NAME' already exists."
fi
conda activate $ENV_NAME
echo "Python version: $(python --version)"
echo "Working directory: $(pwd)"

pip3 install transformers

python llm.model.test.py