#!/bin/bash

#SBATCH --job-name=SafetyNeurons    # Job name
#SBATCH --output=job.%j.out         # Name of output file
#SBATCH --cpus-per-task=1           # Your program is mostly single-threaded
#SBATCH --gres=gpu                  # Request a GPU
#SBATCH --mem=16G                   # Increase memory request
#SBATCH --time=01:00:00             # Max run time
#SBATCH --partition=acltr           # Partition

echo "Running on $(hostname):"
module load Anaconda3
source activate /home/hheg_stli/condaenvs/myenv

echo "Python version: $(python --version)"
echo "Working directory: $(pwd)"


python createTestingData.py

echo "jobs done! :)"
